version: '3.3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: US/Eastern
    ports:
      - "3307:3307"
  web:
    build: .
    ports:
      - "3100:3100"
    depends_on:
      - db



