version: '3.3'

services:
  db:
    container_name: katakanaDB
    tty: true
    image: mariadb
    env_file:
      - .env
    environment:
      TZ: US/Eastern
    ports:
      - '${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}'
    volumes:
      - katakanaDB_data:/var/lib/mysql

volumes:
  katakanaDB_data:
