version: '3.3'

services:
  db:
    container_name: katakanaDB
    tty: true
    image: mariadb
    env_file:
      - .env
    environment:
      TZ: US/Eastern
    ports:
      - '3307:3307'
    # expose:
    #   # Opens port on the container
    #   - '${MYSQL_PORT}'



